application: nexus-ga
version: alpha
runtime: php55
api_version: 1
threadsafe: yes
default_expiration: 1h

handlers:
#CORE
# Serve php scripts.
- url: /(.+\.php)$
  script: \1

- url: /core/(.*)/widgets/(.*).widget$
  static_files: core/\1/widgets/\2.widget
  upload: core/(.*)/widgets/(.*).widget$
  application_readable: true

- url: /core/(.*)/templates/(.*).template$
  static_files: core/\1/templates/\2.template
  upload: core/(.*)/templates/(.*).template$
  application_readable: true

- url: /core/(.*)/images/(.*).png$
  static_files: core/\1/images/\2.png
  upload: core/(.*)/images/(.*).png$
  application_readable: true

- url: /core/(.*)/stylesheets/(.*).css$
  static_files: core/\1/stylesheets/\2.css
  upload: core/(.*)/stylesheets/(.*).css$
  application_readable: true

- url: /core/(.*)/fonts/(.*)$
  static_files: core/\1/fonts/\2
  upload: core/(.*)/fonts/(.*)$
  application_readable: true

- url: /core/(.*)/scripts/(.*).js$
  static_files: core/\1/scripts/\2.js
  upload: core/(.*)/scripts/(.*).js$
  application_readable: true

- url: /core/(.*)/scripts/(.*).css$
  static_files: core/\1/scripts/\2.css
  upload: core/(.*)/scripts/(.*).css$
  application_readable: true

- url: /plugins/(.*)/templates/(.*).template$
  static_files: plugins/\1/templates/\2.template
  upload: plugins/(.*)/templates/(.*).template$
  application_readable: true

- url: /plugins/(.*)/widgets/(.*).widget$
  static_files: plugins/\1/widgets/\2.widget
  upload: plugins/(.*)/widgets/(.*).widget$
  application_readable: true

- url: /plugins/(.*)/stylesheets/(.*).css$
  static_files: plugins/\1/stylesheets/\2.css
  upload: plugins/(.*)/stylesheets/(.*).css$
  application_readable: true

- url: /plugins/(.*)/fonts/(.*)$
  static_files: plugins/\1/fonts/\2
  upload: plugins/(.*)/fonts/(.*)$
  application_readable: true

- url: /plugins/(.*)/scripts/(.*).js$
  static_files: plugins/\1/scripts/\2.js
  upload: plugins/(.*)/scripts/(.*).js$
  application_readable: true

- url: /plugins/(.*)/(.*).php$
  static_files: plugins/\1/\2.php
  upload: plugins/(.*)/(.*).php$
  application_readable: true

- url: /fonts/*
  static_dir: fonts/

- url: /images/*
  static_dir: images/

- url: /fonts/*
  static_dir: fonts/

- url: /scripts/*
  static_dir: scripts/

#TODO check error handlers for the app.yaml
#TODO go through app.yaml dox to see if i can improve this page

#CORE
- url: .*
  script: /core/nexus/engine.php
  login: required

skip_files:
- ^(.*/)?\.DS_Store$
- ^(.*/)?\.scss$
