application: nexus-ga
version: 1
runtime: php55
api_version: 1

handlers:
-   url: /images/*
    static_dir: images/

-   url: /stylesheets/*
    static_dir: stylesheets/

-   url: /fonts/*
    static_dir: fonts/

-   url: /scripts/*
    static_dir: scripts/

-   url: /.*
    script: /modules/nexus/nexus.php 