services:
    nexus_symfony.example:
        class: Nexus\SymfonyBundle\Example

#      nexus_symfony.example:
#        class: Nexus\SymfonyBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
