# Copyright 2015 Google Inc. All Rights Reserved.
imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

# Force monolog to use syslog
monolog:
    handlers:
        syslog:
            type: syslog
            level: debug

assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com
